# Discord Bot Token
DISCORD_TOKEN = 'DISCORD_TOKEN'

# Reddit API Credentials
REDDIT_CLIENT_ID = 'YOUR_REDDIT_CLIENT_ID'
REDDIT_CLIENT_SECRET = 'YOUR_REDDIT_CLIENT_SECRET'
REDDIT_USER_AGENT = 'YOUR_REDDIT_USER_AGENT'

# Discord Channel ID
CHANNEL_ID = 'CHANNEL_ID'